# Generated by Django 5.1.2 on 2024-10-27 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inv', '0006_alter_producto_options_alter_producto_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='producto',
            options={'verbose_name_plural': 'Productos'},
        ),
    ]
