# Generated by Django 5.1.2 on 2024-11-01 03:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cmp', '0002_alter_proveedor_email_comprasenc_comprasdet'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comprasdet',
            options={'verbose_name': 'Detalle Compra', 'verbose_name_plural': 'Detalles Compras'},
        ),
    ]
